.TH "enumValueSpec" 3 "Wed Feb 19 2025" "Version 0.9.2.0" "argparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enumValueSpec \- enum value structure for enum parser argument creation  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <varg_clib\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBenumValueName\fP"
.br
.ti -1c
.RI "int \fBenumValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
enum value structure for enum parser argument creation 

.SH "Author"
.PP 
Generated automatically by Doxygen for argparse from the source code\&.
