/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike
*
* MIT License
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in
* the Software without restriction, including without limitation the rights to
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:
*
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*
*
* This file was autogenerated by GenerateBaseLangFilesV1.0.0.0 do not edit
*
* ----------------------------------------------------------------------------*/

// Includes
#include "mock_ParserStringListInterface.h"

/**
 * @file mock_ParserStringListInterface.cpp
 * @defgroup LocalLanguageSelection Local language detection and selection utility
 * @ingroup LocalLanguageSelection
 * @{
 */

using namespace argparser;
using ::testing::StrictMock;
using ::testing::Return;
using stringMockptr = StrictMock<mock_ParserStringListInterface>*;

/**
 * @brief Mock version of ParserStringListInterface::getLocalParserStringListInterface()
 *
 * @return std::shared_ptr<ParserStringListInterface> Current mock object
 */
std::shared_ptr<ParserStringListInterface> ParserStringListInterface::getLocalParserStringListInterface()
{
    std::shared_ptr<ParserStringListInterface> retPtr = std::make_shared< StrictMock<mock_ParserStringListInterface> >();

#if defined(CONSTRUCTOR_GET_HELP_STRING)
    stringMockptr stringMock = reinterpret_cast<stringMockptr> (retPtr.get());   // NOLINT
    EXPECT_CALL(*stringMock, getHelpString()).WillOnce(Return("mock getHelpString"));
#endif //defined(CONSTRUCTOR_GET_HELP_STRING)

    return retPtr;
}

/**@}*/
