/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike
*
* MIT License
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in
* the Software without restriction, including without limitation the rights to
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:
*
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*
*
* This file was autogenerated by GenerateBaseLangFilesV1.0.0.0 do not edit
*
* ----------------------------------------------------------------------------*/

// Includes
#include <cstddef>
#include <cstdlib>
#include <memory>
#include <string>
#include <gmock/gmock.h>
#include "ParserStringListInterface.h"
#include "mock_ParserStringListInterface.h"

/**
 * @file mock_ParserStringListInterface.cpp
 * @defgroup LocalLanguageSelection Local language detection and selection utility
 * @ingroup LocalLanguageSelection
 * @{
 */

using namespace argparser;

//static std::shared_ptr<mock_ParserStringListInterface> currentMock;  // NOLINT

/**
 * @brief Set the currentMock return variable to the input test mock object
 */
//mock_ParserStringListInterface::mock_ParserStringListInterface()
//{
//    if (currentMock.get() == nullptr)   // NOLINT
//    {
//        currentMock = std::shared_ptr<mock_ParserStringListInterface>(this);
//    }
//}

/**
 * @brief Mock version of ParserStringListInterface::getLocalParserStringListInterface()
 *
 * @return std::shared_ptr<ParserStringListInterface> Current mock object
 */
std::shared_ptr<ParserStringListInterface> ParserStringListInterface::getLocalParserStringListInterface()
{
    return std::make_shared< ::testing::StrictMock<mock_ParserStringListInterface> >();
}

/**@}*/
