/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateBaseLangFilesV1.0.0.0 do not edit      
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <cstddef>
#include <cstdlib>
#include <memory>
#include <string>
#include <gmock/gmock.h>
#include "ParserStringListInterface.h"

/**
 * @file mock_ParserStringListInterface.h
 * @defgroup LocalLanguageSelection Local language detection and selection utility
 * @ingroup LocalLanguageSelection
 * @{
 */

#pragma once
namespace argparser {

/**
 * @brief Mock Parser error/help string generation interface
 */
class mock_ParserStringListInterface : public ParserStringListInterface
{
    public:
        mock_ParserStringListInterface() = default;
        mock_ParserStringListInterface(const mock_ParserStringListInterface& other) = delete;
        mock_ParserStringListInterface(mock_ParserStringListInterface&& other) = delete;
        mock_ParserStringListInterface& operator=(const mock_ParserStringListInterface& other) = delete;
        mock_ParserStringListInterface& operator=(mock_ParserStringListInterface&& other) = delete;
        virtual ~mock_ParserStringListInterface() = default;

        MOCK_METHOD(parserstr, getLangIsoCode, (), (const, final));
        MOCK_METHOD(parserstr, getNotListTypeMessage, (int nargs), (final));
        MOCK_METHOD(parserstr, getUnknownArgumentMessage, (parserstr keyString), (final));
        MOCK_METHOD(parserstr, getInvalidAssignmentMessage, (parserstr keyString), (final));
        MOCK_METHOD(parserstr, getAssignmentFailedMessage, (parserstr keyString, parserstr valueString), (final));
        MOCK_METHOD(parserstr, getMissingAssignmentMessage, (parserstr keyString), (final));
        MOCK_METHOD(parserstr, getMissingListAssignmentMessage, (parserstr keyString, size_t nargsExpected, size_t nargsFound), (final));
        MOCK_METHOD(parserstr, getTooManyAssignmentMessage, (parserstr keyString, size_t nargsExpected, size_t nargsFound), (final));
        MOCK_METHOD(parserstr, getMissingArgumentMessage, (parserstr keyString), (final));
        MOCK_METHOD(parserstr, getArgumentCreationError, (parserstr keyString), (final));
        MOCK_METHOD(parserstr, getUsageMessage, (), (const, final));
        MOCK_METHOD(parserstr, getPositionalArgumentsMessage, (), (const, final));
        MOCK_METHOD(parserstr, getSwitchArgumentsMessage, (), (const, final));
        MOCK_METHOD(parserstr, getHelpString, (), (const, final));
        MOCK_METHOD(parserstr, getEnvArgumentsMessage, (), (const, final));
        MOCK_METHOD(parserstr, getEnvironmentNoFlags, (parserstr envKeyString), (final));
        MOCK_METHOD(parserstr, getRequiredEnvironmentArgMissing, (parserstr envKeyString), (final));
        MOCK_METHOD(parserstr, getJsonArgumentsMessage, (), (const, final));
        MOCK_METHOD(parserstr, getXmlArgumentsMessage, (), (const, final));
}; // end of mock_ParserStringListInterface class

}; // end of namespace argparser

/**@}*/
