.TH "config_json_parse/inc/config_json_parse.h" 3 "Sat Sep 14 2024" "Version 0.9.2.0" "argparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_json_parse/inc/config_json_parse.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'varg_intf\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBargparser::config_json_parse\fP"
.br
.RI "JSON configuration file parser\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for argparse from the source code\&.
