.TH "libvarg" 3 "Sat Sep 14 2024" "Version 0.9.2.0" "argparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libvarg \- Argument value storage implementation
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlistvarg\&.h\fP"
.br
.ti -1c
.RI "file \fBvarg\&.h\fP"
.br
.ti -1c
.RI "file \fBvargenum\&.h\fP"
.br
.ti -1c
.RI "file \fBvargincrement\&.h\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for argparse from the source code\&.
