.TH "varg/inc/vargincrement.h" 3 "Sat Sep 14 2024" "Version 0.9.2.0" "argparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
varg/inc/vargincrement.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'varg_intf\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBargparser::vargincrement\fP"
.br
.RI "Variable argument type template class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for argparse from the source code\&.
