/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateLangFilesV1.0.0.0 do not edit          
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <sstream>
#include "ParserStringListInterface.h"
#include "ParserStringListInterfaceSimplifiedchinese.h"
using namespace argparser;
using parser_str_stream = std::stringstream;


/**
 * @file ParserStringListInterface.cpp
 * @defgroup LocalLanguageSelection Local language detection and selection utility
 * @ingroup LocalLanguageSelection
 * @{
 */

/**
 * @brief Get the ISO 639 set 1 language code for this object
 * 
 * @return parserstr - ISO 639 set 1 language code
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getLangIsoCode() const
{return ("zh");}

/**
 * @brief Return non-list varg error message
 * 
 * @param nargs input nargs value
 * 
 * @return parserstr - Non-list varg error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getNotListTypeMessage(int nargs)
{parser_str_stream parserstr;  parserstr << "只有列表类型参数可以具有" << nargs << "的参数数量"; return parserstr.str();}
/**
 * @brief Return unknown parser key error message
 * 
 * @param keyString Unknown key
 * 
 * @return parserstr - Unknown parser key error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getUnknownArgumentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "未知参数：" << keyString; return parserstr.str();}
/**
 * @brief Return varg invalid assignment error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Varg key invalid assignment error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getInvalidAssignmentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "“" << keyString << "”赋值无效"; return parserstr.str();}
/**
 * @brief Return varg assignment failed error message
 * 
 * @param keyString Error key
 * @param valueString Assignment value
 * 
 * @return parserstr - Varg key assignment failed error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getAssignmentFailedMessage(parserstr keyString, parserstr valueString)
{parser_str_stream parserstr;  parserstr << "“" << keyString << "”、“" << valueString << "”赋值失败"; return parserstr.str();}
/**
 * @brief Return varg missing assignment error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Varg key missing value assignment error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getMissingAssignmentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "“" << keyString << "”缺少赋值"; return parserstr.str();}
/**
 * @brief Return varg missing list value assignment error message
 * 
 * @param keyString Error key
 * @param nargsExpected Expected assignment list length
 * @param nargsFound Input assignment list length
 * 
 * @return parserstr - Varg key input value list too short error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getMissingListAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound)
{parser_str_stream parserstr;  parserstr << "“" << keyString << "”缺少赋值。预期：" << nargsExpected << "，找到：" << nargsFound << " 参数"; return parserstr.str();}
/**
 * @brief Return varg missing list value assignment error message
 * 
 * @param keyString Error key
 * @param nargsExpected Expected assignment list length
 * @param nargsFound Input assignment list length
 * 
 * @return parserstr - Varg key input value list too long error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getTooManyAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound)
{parser_str_stream parserstr;  parserstr << "“" << keyString << "”赋值过多。预期：" << nargsExpected << "，找到：" << nargsFound << " 参数"; return parserstr.str();}
/**
 * @brief Return required varg missing error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Required varg key missing error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getMissingArgumentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "缺少“" << keyString << "”必需参数"; return parserstr.str();}
/**
 * @brief Return parser add varg failure error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Parser varg add failure message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getArgumentCreationError(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "参数添加失败：" << keyString; return parserstr.str();}
/**
 * @brief Return usage help message
 * 
 * @return parserstr - Usage help message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getUsageMessage() const
{parser_str_stream parserstr;  parserstr << "用法："; return parserstr.str();}
/**
 * @brief Return positional argument help message
 * 
 * @return parserstr - Positional argument help message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getPositionalArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "位置参数："; return parserstr.str();}
/**
 * @brief Return optional argument help message
 * 
 * @return parserstr - Optional argument help message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getSwitchArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "可选参数："; return parserstr.str();}
/**
 * @brief Return default help switch help message
 * 
 * @return parserstr - Default help argument help message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getHelpString() const
{parser_str_stream parserstr;  parserstr << "显示此帮助消息并退出"; return parserstr.str();}
/**
 * @brief Return environment parser argument help header
 * 
 * @return parserstr - Environment parser argument help header message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getEnvArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "定义的环境值："; return parserstr.str();}
/**
 * @brief Return environment parser add flag varg failure error message
 * 
 * @param envKeyString Flag key
 * 
 * @return parserstr - Environment parser add flag varg failure message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getEnvironmentNoFlags(parserstr envKeyString)
{parser_str_stream parserstr;  parserstr << "环境值" << envKeyString << " narg 必须> 0"; return parserstr.str();}
/**
 * @brief Return environment parser required varg missing error message
 * 
 * @param envKeyString Flag key
 * 
 * @return parserstr - Environment parser required varg missing error message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getRequiredEnvironmentArgMissing(parserstr envKeyString)
{parser_str_stream parserstr;  parserstr << "必须定义环境值" << envKeyString; return parserstr.str();}
/**
 * @brief Return json parser argument help header
 * 
 * @return parserstr - JSON parser argument help header message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getJsonArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "可用的 JSON 参数值："; return parserstr.str();}
/**
 * @brief Return xml parser argument help header
 * 
 * @return parserstr - XML parser argument help header message
 */
parserstr ParserStringListInterfaceSimplifiedchinese::getXmlArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "可用的 XML 参数值："; return parserstr.str();}

/**@}*/
