/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike
* 
* MIT License
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in
* the Software without restriction, including without limitation the rights to
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:
* 
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
* 
* 
* This file was autogenerated by GenerateLangFilesv0.5.0 do not edit
* 
* ----------------------------------------------------------------------------*/

// Includes
#include "ParserStringListInterface.h"
#include "ParserStringListInterfaceEnglish.h"
#include "ParserStringListInterfaceSpanish.h"
#include "ParserStringListInterfaceFrench.h"
#include "ParserStringListInterfaceSimplifiedchinese.h"

/**
 * @file ParserStringListInterface.cpp
 * @defgroup LocalLanguageSelection Local language detection and selection utility
 * @ingroup LocalLanguageSelection
 * @{
 */

using namespace argparser;

#if (defined(__linux__) || defined(__unix__))
#include <cstdlib>
#include <regex>

// NOLINTBEGIN

/**
 * @brief Determine the correct local language class from the input LANG environment setting
 * 
 * @param langId Current LANG value from the program environment
 * 
 * @return std::shared_ptr<ParserStringListInterface> - Shared pointer to ParserStringListInterface<lang> based on OS
 *                                                      local language
 */
std::shared_ptr<ParserStringListInterface> getParserStringListInterface_Linux(const char* langId)
{
    // Check for valid input
    if (nullptr != langId)
    {
        // Break the string into its components
        std::cmatch search_match;
        std::regex search_regex("^([a-z]{2})_([A-Z]{2})\\.(UTF-[0-9]{1,2})");
        bool matched = std::regex_match(langId, search_match, search_regex);

        // Determine the language
        if (matched && (search_match[1].str() == "en"))
        {
            return std::make_shared<ParserStringListInterfaceEnglish>();
        }
        else if (matched && (search_match[1].str() == "es"))
        {
            return std::make_shared<ParserStringListInterfaceSpanish>();
        }
        else if (matched && (search_match[1].str() == "fr"))
        {
            return std::make_shared<ParserStringListInterfaceFrench>();
        }
        else if (matched && (search_match[1].str() == "zh"))
        {
            return std::make_shared<ParserStringListInterfaceSimplifiedchinese>();
        }
        else //unknown language code, use default language
        {
            return std::make_shared<ParserStringListInterfaceEnglish>();
        }
    }
    else // null pointer input, use default language
    {
        return std::make_shared<ParserStringListInterfaceEnglish>();
    } // end of if(nullptr != langId)
} // end of getParserStringListInterface_Linux()
// NOLINTEND
#endif // (defined(__linux__) || defined(__unix__))

#if (defined(_WIN64) || defined(_WIN32))
#include <windows.h>

/**
 * @brief Determine the correct local language class from the input LANGID value
 * 
 * @param lang_id Return value from GetUserDefaultUILanguage() call
 * 
 * @return std::shared_ptr<ParserStringListInterface> - Shared pointer to ParserStringListInterface<lang> based on OS
 *                                                      local language
 */
std::shared_ptr<ParserStringListInterface> getParserStringListInterface_Windows(LANGID lang_id)
{
    switch(lang_id & 0x0FF)
    {
        case 0x9:
            return std::make_shared<ParserStringListInterfaceEnglish>();
            break;
        case 0xa:
            return std::make_shared<ParserStringListInterfaceSpanish>();
            break;
        case 0xc:
            return std::make_shared<ParserStringListInterfaceFrench>();
            break;
        case 0x4:
            return std::make_shared<ParserStringListInterfaceSimplifiedchinese>();
            break;
        default:
            return std::make_shared<ParserStringListInterfaceEnglish>();
    }
} // end of getParserStringListInterface_Windows()
#endif // (defined(_WIN64) || defined(_WIN32))

/**
 * @brief Determine the OS use OS specific functions to determine the correct local language based on the OS specific
 *        local language setting and return the correct class object
 * 
 * @return std::shared_ptr<ParserStringListInterface> - Shared pointer to ParserStringListInterface<lang> based on OS
 *                                                      local language
 */
std::shared_ptr<ParserStringListInterface> ParserStringListInterface::getLocalParserStringListInterface()
{
#if (defined(__linux__) || defined(__unix__))
    const char* langId = getenv("LANG");
    return getParserStringListInterface_Linux(langId);
#elif (defined(_WIN64) || defined(_WIN32))
    LANGID lang_id = GetUserDefaultUILanguage();
    return getParserStringListInterface_Windows(lang_id);
#else // not defined os
    #error No language generation method defined for this OS
#endif // defined os
} // end of ParserStringListInterface::getLocalParserStringListInterface()

/**@} */
