/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateLangFilesV1.0.0.0 do not edit          
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <sstream>
#include "ParserStringListInterface.h"
#include "ParserStringListInterfaceFrench.h"
using namespace argparser;
using parser_str_stream = std::stringstream;


/**
 * @file ParserStringListInterface.cpp
 * @defgroup LocalLanguageSelection Local language detection and selection utility
 * @ingroup LocalLanguageSelection
 * @{
 */

/**
 * @brief Get the ISO 639 set 1 language code for this object
 * 
 * @return parserstr - ISO 639 set 1 language code
 */
parserstr ParserStringListInterfaceFrench::getLangIsoCode() const
{return ("fr");}

/**
 * @brief Return non-list varg error message
 * 
 * @param nargs input nargs value
 * 
 * @return parserstr - Non-list varg error message
 */
parserstr ParserStringListInterfaceFrench::getNotListTypeMessage(int nargs)
{parser_str_stream parserstr;  parserstr << "Seuls les arguments de type liste peuvent avoir un nombre d'arguments de " << nargs; return parserstr.str();}
/**
 * @brief Return unknown parser key error message
 * 
 * @param keyString Unknown key
 * 
 * @return parserstr - Unknown parser key error message
 */
parserstr ParserStringListInterfaceFrench::getUnknownArgumentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "Argument inconnu : " << keyString; return parserstr.str();}
/**
 * @brief Return varg invalid assignment error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Varg key invalid assignment error message
 */
parserstr ParserStringListInterfaceFrench::getInvalidAssignmentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "Affectation non valide « " << keyString << " »"; return parserstr.str();}
/**
 * @brief Return varg assignment failed error message
 * 
 * @param keyString Error key
 * @param valueString Assignment value
 * 
 * @return parserstr - Varg key assignment failed error message
 */
parserstr ParserStringListInterfaceFrench::getAssignmentFailedMessage(parserstr keyString, parserstr valueString)
{parser_str_stream parserstr;  parserstr << "Échec de l'affectation de « " << keyString << " », « " << valueString << " »"; return parserstr.str();}
/**
 * @brief Return varg missing assignment error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Varg key missing value assignment error message
 */
parserstr ParserStringListInterfaceFrench::getMissingAssignmentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "Valeur d'affectation manquante \"" << keyString << "\""; return parserstr.str();}
/**
 * @brief Return varg missing list value assignment error message
 * 
 * @param keyString Error key
 * @param nargsExpected Expected assignment list length
 * @param nargsFound Input assignment list length
 * 
 * @return parserstr - Varg key input value list too short error message
 */
parserstr ParserStringListInterfaceFrench::getMissingListAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound)
{parser_str_stream parserstr;  parserstr << "Valeur(s) d'affectation manquante(s) pour « " << keyString << " ». Arguments attendus : " << nargsExpected << ". Arguments trouvés : " << nargsFound << "."; return parserstr.str();}
/**
 * @brief Return varg missing list value assignment error message
 * 
 * @param keyString Error key
 * @param nargsExpected Expected assignment list length
 * @param nargsFound Input assignment list length
 * 
 * @return parserstr - Varg key input value list too long error message
 */
parserstr ParserStringListInterfaceFrench::getTooManyAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound)
{parser_str_stream parserstr;  parserstr << "« " << keyString << " » : trop de valeurs d'affectation. Arguments attendus : " << nargsExpected << ". Arguments trouvés : " << nargsFound << "."; return parserstr.str();}
/**
 * @brief Return required varg missing error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Required varg key missing error message
 */
parserstr ParserStringListInterfaceFrench::getMissingArgumentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "L'argument requis « " << keyString << " » est manquant"; return parserstr.str();}
/**
 * @brief Return parser add varg failure error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Parser varg add failure message
 */
parserstr ParserStringListInterfaceFrench::getArgumentCreationError(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "Échec de l'ajout d'argument : " << keyString; return parserstr.str();}
/**
 * @brief Return usage help message
 * 
 * @return parserstr - Usage help message
 */
parserstr ParserStringListInterfaceFrench::getUsageMessage() const
{parser_str_stream parserstr;  parserstr << "Usage:"; return parserstr.str();}
/**
 * @brief Return positional argument help message
 * 
 * @return parserstr - Positional argument help message
 */
parserstr ParserStringListInterfaceFrench::getPositionalArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Arguments positionnels :"; return parserstr.str();}
/**
 * @brief Return optional argument help message
 * 
 * @return parserstr - Optional argument help message
 */
parserstr ParserStringListInterfaceFrench::getSwitchArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Arguments facultatifs :"; return parserstr.str();}
/**
 * @brief Return default help switch help message
 * 
 * @return parserstr - Default help argument help message
 */
parserstr ParserStringListInterfaceFrench::getHelpString() const
{parser_str_stream parserstr;  parserstr << "afficher ce message d'aide et quitter"; return parserstr.str();}
/**
 * @brief Return environment parser argument help header
 * 
 * @return parserstr - Environment parser argument help header message
 */
parserstr ParserStringListInterfaceFrench::getEnvArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Valeurs environnementales définies :"; return parserstr.str();}
/**
 * @brief Return environment parser add flag varg failure error message
 * 
 * @param envKeyString Flag key
 * 
 * @return parserstr - Environment parser add flag varg failure message
 */
parserstr ParserStringListInterfaceFrench::getEnvironmentNoFlags(parserstr envKeyString)
{parser_str_stream parserstr;  parserstr << "La valeur d'environnement " << envKeyString << " narg doit être > 0"; return parserstr.str();}
/**
 * @brief Return environment parser required varg missing error message
 * 
 * @param envKeyString Flag key
 * 
 * @return parserstr - Environment parser required varg missing error message
 */
parserstr ParserStringListInterfaceFrench::getRequiredEnvironmentArgMissing(parserstr envKeyString)
{parser_str_stream parserstr;  parserstr << "La valeur d'environnement " << envKeyString << " doit être définie"; return parserstr.str();}
/**
 * @brief Return json parser argument help header
 * 
 * @return parserstr - JSON parser argument help header message
 */
parserstr ParserStringListInterfaceFrench::getJsonArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Valeurs d'argument JSON disponibles :"; return parserstr.str();}
/**
 * @brief Return xml parser argument help header
 * 
 * @return parserstr - XML parser argument help header message
 */
parserstr ParserStringListInterfaceFrench::getXmlArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Valeurs d'argument XML disponibles :"; return parserstr.str();}

/**@}*/
