/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateLangFilesV1.0.0.0 do not edit          
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <sstream>
#include "ParserStringListInterface.h"
#include "ParserStringListInterfaceEnglish.h"
using namespace argparser;
using parser_str_stream = std::stringstream;


/**
 * @file ParserStringListInterface.cpp
 * @defgroup LocalLanguageSelection Local language detection and selection utility
 * @ingroup LocalLanguageSelection
 * @{
 */

/**
 * @brief Get the ISO 639 set 1 language code for this object
 * 
 * @return parserstr - ISO 639 set 1 language code
 */
parserstr ParserStringListInterfaceEnglish::getLangIsoCode() const
{return ("en");}

/**
 * @brief Return non-list varg error message
 * 
 * @param nargs input nargs value
 * 
 * @return parserstr - Non-list varg error message
 */
parserstr ParserStringListInterfaceEnglish::getNotListTypeMessage(int nargs)
{parser_str_stream parserstr;  parserstr << "Only list type arguments can have an argument count of " << nargs; return parserstr.str();}
/**
 * @brief Return unknown parser key error message
 * 
 * @param keyString Unknown key
 * 
 * @return parserstr - Unknown parser key error message
 */
parserstr ParserStringListInterfaceEnglish::getUnknownArgumentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "Unknown argument: " << keyString; return parserstr.str();}
/**
 * @brief Return varg invalid assignment error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Varg key invalid assignment error message
 */
parserstr ParserStringListInterfaceEnglish::getInvalidAssignmentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "\"" << keyString << "\" invalid assignment"; return parserstr.str();}
/**
 * @brief Return varg assignment failed error message
 * 
 * @param keyString Error key
 * @param valueString Assignment value
 * 
 * @return parserstr - Varg key assignment failed error message
 */
parserstr ParserStringListInterfaceEnglish::getAssignmentFailedMessage(parserstr keyString, parserstr valueString)
{parser_str_stream parserstr;  parserstr << "\"" << keyString << "\", \"" << valueString << "\" assignment failed"; return parserstr.str();}
/**
 * @brief Return varg missing assignment error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Varg key missing value assignment error message
 */
parserstr ParserStringListInterfaceEnglish::getMissingAssignmentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "\"" << keyString << "\" missing assignment value"; return parserstr.str();}
/**
 * @brief Return varg missing list value assignment error message
 * 
 * @param keyString Error key
 * @param nargsExpected Expected assignment list length
 * @param nargsFound Input assignment list length
 * 
 * @return parserstr - Varg key input value list too short error message
 */
parserstr ParserStringListInterfaceEnglish::getMissingListAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound)
{parser_str_stream parserstr;  parserstr << "\"" << keyString << "\" missing assignment value(s). Expected: " << nargsExpected << " found: " << nargsFound << " arguments"; return parserstr.str();}
/**
 * @brief Return varg missing list value assignment error message
 * 
 * @param keyString Error key
 * @param nargsExpected Expected assignment list length
 * @param nargsFound Input assignment list length
 * 
 * @return parserstr - Varg key input value list too long error message
 */
parserstr ParserStringListInterfaceEnglish::getTooManyAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound)
{parser_str_stream parserstr;  parserstr << "\"" << keyString << "\" too many assignment values. Expected: " << nargsExpected << " found: " << nargsFound << " arguments"; return parserstr.str();}
/**
 * @brief Return required varg missing error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Required varg key missing error message
 */
parserstr ParserStringListInterfaceEnglish::getMissingArgumentMessage(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "\"" << keyString << "\" required argument missing"; return parserstr.str();}
/**
 * @brief Return parser add varg failure error message
 * 
 * @param keyString Error key
 * 
 * @return parserstr - Parser varg add failure message
 */
parserstr ParserStringListInterfaceEnglish::getArgumentCreationError(parserstr keyString)
{parser_str_stream parserstr;  parserstr << "Argument add failed: " << keyString; return parserstr.str();}
/**
 * @brief Return usage help message
 * 
 * @return parserstr - Usage help message
 */
parserstr ParserStringListInterfaceEnglish::getUsageMessage() const
{parser_str_stream parserstr;  parserstr << "Usage:"; return parserstr.str();}
/**
 * @brief Return positional argument help message
 * 
 * @return parserstr - Positional argument help message
 */
parserstr ParserStringListInterfaceEnglish::getPositionalArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Positional Arguments:"; return parserstr.str();}
/**
 * @brief Return optional argument help message
 * 
 * @return parserstr - Optional argument help message
 */
parserstr ParserStringListInterfaceEnglish::getSwitchArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Optional Arguments:"; return parserstr.str();}
/**
 * @brief Return default help switch help message
 * 
 * @return parserstr - Default help argument help message
 */
parserstr ParserStringListInterfaceEnglish::getHelpString() const
{parser_str_stream parserstr;  parserstr << "show this help message and exit"; return parserstr.str();}
/**
 * @brief Return environment parser argument help header
 * 
 * @return parserstr - Environment parser argument help header message
 */
parserstr ParserStringListInterfaceEnglish::getEnvArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Defined Environment values:"; return parserstr.str();}
/**
 * @brief Return environment parser add flag varg failure error message
 * 
 * @param envKeyString Flag key
 * 
 * @return parserstr - Environment parser add flag varg failure message
 */
parserstr ParserStringListInterfaceEnglish::getEnvironmentNoFlags(parserstr envKeyString)
{parser_str_stream parserstr;  parserstr << "Environment value " << envKeyString << " narg must be > 0"; return parserstr.str();}
/**
 * @brief Return environment parser required varg missing error message
 * 
 * @param envKeyString Flag key
 * 
 * @return parserstr - Environment parser required varg missing error message
 */
parserstr ParserStringListInterfaceEnglish::getRequiredEnvironmentArgMissing(parserstr envKeyString)
{parser_str_stream parserstr;  parserstr << "Environment value " << envKeyString << " must be defined"; return parserstr.str();}
/**
 * @brief Return json parser argument help header
 * 
 * @return parserstr - JSON parser argument help header message
 */
parserstr ParserStringListInterfaceEnglish::getJsonArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Available JSON argument values:"; return parserstr.str();}
/**
 * @brief Return xml parser argument help header
 * 
 * @return parserstr - XML parser argument help header message
 */
parserstr ParserStringListInterfaceEnglish::getXmlArgumentsMessage() const
{parser_str_stream parserstr;  parserstr << "Available XML argument values:"; return parserstr.str();}

/**@}*/
