/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike
* 
* MIT License
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in
* the Software without restriction, including without limitation the rights to
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:
* 
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
* 
* 
* This file was autogenerated by GenerateBaseLangFilesV0.4.1.0 do not edit
* 
* ----------------------------------------------------------------------------*/

// Includes
#include <gtest/gtest.h>
#include "ParserStringListInterface.h"

/**
 * @file LocalLanguageSelect_Linux_test.cpp
 * @defgroup LocalLanguageSelectionunittest Local language detection and selection utilityunit test
 * @ingroup LocalLanguageSelectionunittest
 * @{
 */

using namespace argparser;
#if (defined(__linux__) || defined(__unix__))

#include <cstdlib>
extern std::shared_ptr<ParserStringListInterface> getParserStringListInterface_Linux(const char* langId);

/**
 * @brief Test getParserStringListInterface_Linux en_AU.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_AU_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_AU.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_BZ.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_BZ_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_BZ.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_CA.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_CA_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_CA.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_CB.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_CB_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_CB.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_GB.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_GB_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_GB.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_IE.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_IE_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_IE.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_JM.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_JM_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_JM.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_NZ.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_NZ_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_NZ.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_PH.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_PH_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_PH.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_TT.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_TT_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_TT.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_US.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_US_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_US.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_ZA.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_ZA_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_ZA.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_ZW.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_ZW_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_ZW.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux en_XX.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, English_unknownRegion_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "en_XX.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_AR.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_AR_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_AR.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_BO.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_BO_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_BO.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_CL.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_CL_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_CL.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_CO.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_CO_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_CO.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_CR.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_CR_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_CR.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_DO.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_DO_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_DO.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_EC.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_EC_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_EC.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_ES.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_ES_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_ES.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_GT.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_GT_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_GT.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_HN.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_HN_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_HN.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_MX.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_MX_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_MX.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_NI.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_NI_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_NI.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_PA.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_PA_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_PA.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_PE.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_PE_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_PE.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_PR.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_PR_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_PR.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_PY.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_PY_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_PY.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_SV.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_SV_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_SV.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_UY.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_UY_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_UY.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_VE.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_VE_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_VE.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux es_XX.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Spanish_unknownRegion_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "es_XX.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux fr_BE.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, French_BE_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "fr_BE.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux fr_CA.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, French_CA_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "fr_CA.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux fr_CH.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, French_CH_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "fr_CH.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux fr_FR.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, French_FR_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "fr_FR.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux fr_LU.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, French_LU_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "fr_LU.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux fr_MC.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, French_MC_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "fr_MC.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux fr_XX.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, French_unknownRegion_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "fr_XX.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux zh_CN.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Simplifiedchinese_CN_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "zh_CN.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux zh_HK.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Simplifiedchinese_HK_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "zh_HK.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux zh_MO.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Simplifiedchinese_MO_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "zh_MO.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux zh_SG.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Simplifiedchinese_SG_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "zh_SG.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux zh_TW.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Simplifiedchinese_TW_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "zh_TW.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux zh_XX.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, Simplifiedchinese_unknownRegion_Selection)
{
    // Generate the test language string object
    std::string testLangCode = "zh_XX.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Linux xx_XX.UTF-8 selection case
 * 
 */
TEST(LinuxSelectFunction, UnknownLanguageDefaultSelection)
{
    // Generate the test language string object
    std::string testLangCode = "xx_XX.UTF-8";
    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Linux(testLangCode.c_str());
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}
#endif // (defined(__linux__) || defined(__unix__))

// Execute the tests
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

/**@} */
