/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateBaseLangFilesV1.0.0.0 do not edit      
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <windows.h>
#include <gtest/gtest.h>
#include "ParserStringListInterface.h"

/**
 * @file LocalLanguageSelect_Windows_test.cpp
 * @defgroup LocalLanguageSelectionunittest Local language detection and selection utilityunit test
 * @ingroup LocalLanguageSelectionunittest
 * @{
 */

using namespace argparser;
#if (defined(_WIN64) || defined(_WIN32))
extern std::shared_ptr<ParserStringListInterface> getParserStringListInterface_Windows(LANGID langId);
/**
 * @brief Test getParserStringListInterface_Windows 3081 selection case
 * 
 */
TEST(WindowsSelectFunction, English_3081_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(3081);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 10249 selection case
 * 
 */
TEST(WindowsSelectFunction, English_10249_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(10249);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 4105 selection case
 * 
 */
TEST(WindowsSelectFunction, English_4105_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(4105);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 9225 selection case
 * 
 */
TEST(WindowsSelectFunction, English_9225_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(9225);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 2057 selection case
 * 
 */
TEST(WindowsSelectFunction, English_2057_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(2057);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 16393 selection case
 * 
 */
TEST(WindowsSelectFunction, English_16393_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(16393);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 6153 selection case
 * 
 */
TEST(WindowsSelectFunction, English_6153_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(6153);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 8201 selection case
 * 
 */
TEST(WindowsSelectFunction, English_8201_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(8201);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 5129 selection case
 * 
 */
TEST(WindowsSelectFunction, English_5129_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(5129);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 13321 selection case
 * 
 */
TEST(WindowsSelectFunction, English_13321_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(13321);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 7177 selection case
 * 
 */
TEST(WindowsSelectFunction, English_7177_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(7177);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 11273 selection case
 * 
 */
TEST(WindowsSelectFunction, English_11273_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(11273);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 1033 selection case
 * 
 */
TEST(WindowsSelectFunction, English_1033_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(1033);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 12297 selection case
 * 
 */
TEST(WindowsSelectFunction, English_12297_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(12297);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 9 selection case
 * 
 */
TEST(WindowsSelectFunction, English_unknownRegion_009_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(9);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 65289 selection case
 * 
 */
TEST(WindowsSelectFunction, English_unknownRegion_FF9_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(65289);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 11274 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_11274_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(11274);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 16394 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_16394_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(16394);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 13322 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_13322_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(13322);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 9226 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_9226_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(9226);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 5130 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_5130_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(5130);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 7178 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_7178_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(7178);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 12298 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_12298_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(12298);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 17418 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_17418_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(17418);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 4106 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_4106_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(4106);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 18442 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_18442_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(18442);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 2058 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_2058_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(2058);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 19466 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_19466_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(19466);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 6154 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_6154_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(6154);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 15370 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_15370_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(15370);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 10250 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_10250_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(10250);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 20490 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_20490_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(20490);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 1034 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_1034_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(1034);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 14346 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_14346_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(14346);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 8202 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_8202_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(8202);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 10 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_unknownRegion_0010_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(10);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 65290 selection case
 * 
 */
TEST(WindowsSelectFunction, Spanish_unknownRegion_FF10_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(65290);
    EXPECT_STREQ("es", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 2060 selection case
 * 
 */
TEST(WindowsSelectFunction, French_2060_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(2060);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 11276 selection case
 * 
 */
TEST(WindowsSelectFunction, French_11276_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(11276);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 3084 selection case
 * 
 */
TEST(WindowsSelectFunction, French_3084_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(3084);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 9228 selection case
 * 
 */
TEST(WindowsSelectFunction, French_9228_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(9228);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 12300 selection case
 * 
 */
TEST(WindowsSelectFunction, French_12300_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(12300);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 1036 selection case
 * 
 */
TEST(WindowsSelectFunction, French_1036_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(1036);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 5132 selection case
 * 
 */
TEST(WindowsSelectFunction, French_5132_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(5132);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 13324 selection case
 * 
 */
TEST(WindowsSelectFunction, French_13324_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(13324);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 6156 selection case
 * 
 */
TEST(WindowsSelectFunction, French_6156_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(6156);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 14348 selection case
 * 
 */
TEST(WindowsSelectFunction, French_14348_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(14348);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 10252 selection case
 * 
 */
TEST(WindowsSelectFunction, French_10252_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(10252);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 4108 selection case
 * 
 */
TEST(WindowsSelectFunction, French_4108_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(4108);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 7180 selection case
 * 
 */
TEST(WindowsSelectFunction, French_7180_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(7180);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 12 selection case
 * 
 */
TEST(WindowsSelectFunction, French_unknownRegion_0012_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(12);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 65292 selection case
 * 
 */
TEST(WindowsSelectFunction, French_unknownRegion_FF12_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(65292);
    EXPECT_STREQ("fr", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 2052 selection case
 * 
 */
TEST(WindowsSelectFunction, Simplifiedchinese_2052_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(2052);
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 3076 selection case
 * 
 */
TEST(WindowsSelectFunction, Simplifiedchinese_3076_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(3076);
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 5124 selection case
 * 
 */
TEST(WindowsSelectFunction, Simplifiedchinese_5124_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(5124);
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 4100 selection case
 * 
 */
TEST(WindowsSelectFunction, Simplifiedchinese_4100_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(4100);
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 1028 selection case
 * 
 */
TEST(WindowsSelectFunction, Simplifiedchinese_1028_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(1028);
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 4 selection case
 * 
 */
TEST(WindowsSelectFunction, Simplifiedchinese_unknownRegion_004_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(4);
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 65284 selection case
 * 
 */
TEST(WindowsSelectFunction, Simplifiedchinese_unknownRegion_FF4_Selection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(65284);
    EXPECT_STREQ("zh", testVar->getLangIsoCode().c_str());
}

/**
 * @brief Test getParserStringListInterface_Windows 0 selection case
 * 
 */
TEST(WindowsSelectFunction, UnknownLanguageDefaultSelection)
{
    // Generate the test language string object

    std::shared_ptr<ParserStringListInterface> testVar = getParserStringListInterface_Windows(0);
    EXPECT_STREQ("en", testVar->getLangIsoCode().c_str());
}
#endif // ((defined(_WIN64) || defined(_WIN32)))

// Execute the tests
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

/**@}*/
