/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateBaseLangFilesV1.0.0.0 do not edit      
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <gtest/gtest.h>
#include "ParserStringListInterface.h"

/**
 * @file ParserStringListInterface_test.cpp
 * @defgroup LocalLanguageSelectionunittest Local language detection and selection utilityunit test
 * @ingroup LocalLanguageSelectionunittest
 * @{
 */

using namespace argparser;

#if (defined(__linux__) || defined(__unix__))
#include <cstdlib>
extern std::shared_ptr<ParserStringListInterface> getParserStringListInterface_Linux(const char* langId);
#endif // (defined(__linux__) || defined(__unix__))
#if (defined(_WIN64) || defined(_WIN32))
#include "windows.h"
extern std::shared_ptr<ParserStringListInterface> getParserStringListInterface_Windows(LANGID langId);
#endif // (defined(_WIN64) || defined(_WIN32))

/**
 * @brief Test ParserStringListInterface::getLocalParserStringListInterface selection case
 * 
 */
TEST(SelectFunction, TestLocalSelectMethod)
{
#if (defined(__linux__) || defined(__unix__))
    // Get the expected value
    const char* langId = getenv("LANG");
    std::shared_ptr<ParserStringListInterface> localStringParser = getParserStringListInterface_Linux(langId);
#elif (defined(_WIN64) || defined(_WIN32))
    // Get the expected value
    LANGID langId = GetUserDefaultUILanguage();
    std::shared_ptr<ParserStringListInterface> localStringParser = getParserStringListInterface_Windows(langId);
#else // not defined os
    #error No language generation defined for this OS
#endif // defined os

    // Generate the test language string object
    std::shared_ptr<ParserStringListInterface> testVar = ParserStringListInterface::getLocalParserStringListInterface();
    EXPECT_STREQ(localStringParser->getLangIsoCode().c_str(), testVar->getLangIsoCode().c_str());
} // end of ParserStringListInterface::getLocalParserStringListInterface()

// Execute the tests
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

/**@}*/
