/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateLangFilesV1.0.0.0 do not edit          
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <cstdio>
#include <cstring>
#include <sstream>
#include <gtest/gtest.h>
#include "ParserStringListInterface.h"
#include "ParserStringListInterfaceSpanish.h"

/**
 * @file ParserStringListInterface_test.cpp
 * @defgroup LocalLanguageSelectionspanishunittest Local language detection and selection utility spanish unit test
 * @ingroup LocalLanguageSelectionspanishunittest
 * @{
 */

using namespace argparser;
using parser_str_stream = std::stringstream;

// NOLINTBEGIN
TEST(ParserStringListInterfaceSpanish, fetchgetLangIsoCode)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getLangIsoCode();
    EXPECT_STREQ("es", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetNotListTypeMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getNotListTypeMessage(3);
    EXPECT_STREQ("Sólo los argumentos de tipo lista pueden tener un recuento de argumentos de 3", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetUnknownArgumentMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getUnknownArgumentMessage("--myKey");
    EXPECT_STREQ("Argumento desconocido: --myKey", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetInvalidAssignmentMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getInvalidAssignmentMessage("--myKey");
    EXPECT_STREQ("\"--myKey\" asignación no válida", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetAssignmentFailedMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getAssignmentFailedMessage("--myKey", "23");
    EXPECT_STREQ("Falló la asignación de \"--myKey\", \"23\"", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetMissingAssignmentMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getMissingAssignmentMessage("--myKey");
    EXPECT_STREQ("\"--myKey\" valor de asignación faltante", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetMissingListAssignmentMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getMissingListAssignmentMessage("--myKey", 2, 1);
    EXPECT_STREQ("Faltan valores de asignación en \"--myKey\". Se esperaba: 2. Se encontraron: 1. Argumentos.", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetTooManyAssignmentMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getTooManyAssignmentMessage("--myKey", 2, 1);
    EXPECT_STREQ("\"--myKey\" demasiados valores de asignación. Se esperaba: 2. Se encontró: 1. Argumentos.", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetMissingArgumentMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getMissingArgumentMessage("--myKey");
    EXPECT_STREQ("Falta el argumento obligatorio \"--myKey\"", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetArgumentCreationError)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getArgumentCreationError("--myKey");
    EXPECT_STREQ("Error al agregar argumento: --myKey", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetUsageMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getUsageMessage();
    EXPECT_STREQ("Uso:", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetPositionalArgumentsMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getPositionalArgumentsMessage();
    EXPECT_STREQ("Argumentos posicionales:", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetSwitchArgumentsMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getSwitchArgumentsMessage();
    EXPECT_STREQ("Argumentos opcionales:", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetHelpString)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getHelpString();
    EXPECT_STREQ("Mostrar este mensaje de ayuda y salir", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetEnvArgumentsMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getEnvArgumentsMessage();
    EXPECT_STREQ("Valores de entorno definidos:", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetEnvironmentNoFlags)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getEnvironmentNoFlags("MY_ENV_KEY");
    EXPECT_STREQ("El valor del entorno MY_ENV_KEY narg debe ser > 0", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetRequiredEnvironmentArgMissing)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getRequiredEnvironmentArgMissing("MY_ENV_KEY");
    EXPECT_STREQ("Se debe definir el valor de entorno MY_ENV_KEY", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetJsonArgumentsMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getJsonArgumentsMessage();
    EXPECT_STREQ("Valores de argumentos JSON disponibles:", output.c_str());
}

TEST(ParserStringListInterfaceSpanish, printgetXmlArgumentsMessage)
{
    ParserStringListInterfaceSpanish testvar;
    parserstr output = testvar.getXmlArgumentsMessage();
    EXPECT_STREQ("Valores de argumentos XML disponibles:", output.c_str());
}

// NOLINTEND
// Execute the tests
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

/**@}*/
