/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike
* 
* MIT License
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in
* the Software without restriction, including without limitation the rights to
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:
* 
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
* 
* 
* This file was autogenerated by GenerateLangFilesV0.4.1.0 do not edit
* 
* ----------------------------------------------------------------------------*/

// Includes
#include <cstdio>
#include <cstring>
#include <sstream>
#include <gtest/gtest.h>
#include "ParserStringListInterface.h"
#include "ParserStringListInterfaceEnglish.h"

/**
 * @file ParserStringListInterface_test.cpp
 * @defgroup LocalLanguageSelectionenglishunittest Local language detection and selection utility english unit test
 * @ingroup LocalLanguageSelectionenglishunittest
 * @{
 */

using namespace argparser;
using parser_str_stream = std::stringstream;

// NOLINTBEGIN
TEST(ParserStringListInterfaceEnglish, fetchgetLangIsoCode)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getLangIsoCode();
    EXPECT_STREQ("en", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetNotListTypeMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getNotListTypeMessage(3);
    EXPECT_STREQ("Only list type arguments can have an argument count of 3", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetUnknownArgumentMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getUnknownArgumentMessage("--myKey");
    EXPECT_STREQ("Unknown argument: --myKey", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetInvalidAssignmentMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getInvalidAssignmentMessage("--myKey");
    EXPECT_STREQ("\"--myKey\" invalid assignment", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetAssignmentFailedMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getAssignmentFailedMessage("--myKey", "23");
    EXPECT_STREQ("\"--myKey\", \"23\" assignment failed", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetMissingAssignmentMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getMissingAssignmentMessage("--myKey");
    EXPECT_STREQ("\"--myKey\" missing assignment value", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetMissingListAssignmentMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getMissingListAssignmentMessage("--myKey", 2, 1);
    EXPECT_STREQ("\"--myKey\" missing assignment value(s). Expected: 2 found: 1 arguments", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetTooManyAssignmentMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getTooManyAssignmentMessage("--myKey", 2, 1);
    EXPECT_STREQ("\"--myKey\" too many assignment values. Expected: 2 found: 1 arguments", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetMissingArgumentMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getMissingArgumentMessage("--myKey");
    EXPECT_STREQ("\"--myKey\" required argument missing", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetArgumentCreationError)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getArgumentCreationError("--myKey");
    EXPECT_STREQ("Argument add failed: --myKey", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetUsageMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getUsageMessage();
    EXPECT_STREQ("Usage:", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetPositionalArgumentsMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getPositionalArgumentsMessage();
    EXPECT_STREQ("Positional Arguments:", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetSwitchArgumentsMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getSwitchArgumentsMessage();
    EXPECT_STREQ("Optional Arguments:", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetHelpString)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getHelpString();
    EXPECT_STREQ("show this help message and exit", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetEnvArgumentsMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getEnvArgumentsMessage();
    EXPECT_STREQ("Defined Environment values:", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetEnvironmentNoFlags)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getEnvironmentNoFlags("MY_ENV_KEY");
    EXPECT_STREQ("Environment value MY_ENV_KEY narg must be > 0", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetRequiredEnvironmentArgMissing)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getRequiredEnvironmentArgMissing("MY_ENV_KEY");
    EXPECT_STREQ("Environment value MY_ENV_KEY must be defined", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetJsonArgumentsMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getJsonArgumentsMessage();
    EXPECT_STREQ("Available JSON argument values:", output.c_str());
}

TEST(ParserStringListInterfaceEnglish, printgetXmlArgumentsMessage)
{
    ParserStringListInterfaceEnglish testvar;
    parserstr output = testvar.getXmlArgumentsMessage();
    EXPECT_STREQ("Available XML argument values:", output.c_str());
}

// NOLINTEND
// Execute the tests
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

/**@} */
