/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike
* 
* MIT License
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in
* the Software without restriction, including without limitation the rights to
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:
* 
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
* 
* 
* This file was autogenerated by GenerateLangFilesv0.5.0 do not edit
* 
* ----------------------------------------------------------------------------*/

// Includes
#include <gtest/gtest.h>
#include "ParserStringListInterface.h"
#include "ParserStringListInterfaceSimplifiedchinese.h"

/**
 * @file ParserStringListInterfaceSimplifiedchinese_test.cpp
 * @defgroup LocalLanguageSelectionunittest Local language detection and selection utilityunit test
 * @ingroup LocalLanguageSelectionunittest
 * @{
 */

using namespace argparser;
TEST(ParserStringListInterfaceSimplifiedchinese, fetchgetLangIsoCode)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getLangIsoCode();
    EXPECT_STREQ("zh", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetNotListTypeMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getNotListTypeMessage(3);
    EXPECT_STREQ("只有列表类型参数可以具有3的参数数量", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetUnknownArgumentMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getUnknownArgumentMessage("--myKey");
    EXPECT_STREQ("未知参数：--myKey", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetInvalidAssignmentMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getInvalidAssignmentMessage("--myKey");
    EXPECT_STREQ("“--myKey”赋值无效", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetAssignmentFailedMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getAssignmentFailedMessage("--myKey", "23");
    EXPECT_STREQ("“--myKey”、“23”赋值失败", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetInvalidValueAssignmentMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getInvalidValueAssignmentMessage("--myKey", "23", "integer", "<-100:100>");
    EXPECT_STREQ("“--myKey”、“23”输入无效。预期：integer、<-100:100>", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetOutOfRangeAssignmentMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getOutOfRangeAssignmentMessage("--myKey", "23", "<-100:100>");
    EXPECT_STREQ("“--myKey”、“23”超出范围。有效范围：<-100:100>", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetMissingAssignmentMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getMissingAssignmentMessage("--myKey");
    EXPECT_STREQ("“--myKey”缺少赋值", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetMissingListAssignmentMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getMissingListAssignmentMessage("--myKey", 2, 1);
    EXPECT_STREQ("“--myKey”缺少赋值。预期：2，找到：1 参数", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetTooManyAssignmentMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getTooManyAssignmentMessage("--myKey", 2, 1);
    EXPECT_STREQ("“--myKey”赋值过多。预期：2，找到：1 参数", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetMissingArgumentMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getMissingArgumentMessage("--myKey");
    EXPECT_STREQ("缺少“--myKey”必需参数", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetStorageNullptrMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getStorageNullptrMessage("--myKey");
    EXPECT_STREQ("“--myKey”变量存储为NULL", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetArgumentCreationError)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getArgumentCreationError("--myKey");
    EXPECT_STREQ("参数添加失败：--myKey", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetUsageMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getUsageMessage();
    EXPECT_STREQ("用法：", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetPositionalArgumentsMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getPositionalArgumentsMessage();
    EXPECT_STREQ("位置参数：", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetSwitchArgumentsMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getSwitchArgumentsMessage();
    EXPECT_STREQ("可选参数：", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetHelpString)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getHelpString();
    EXPECT_STREQ("显示此帮助消息并退出", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetEnvArgumentsMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getEnvArgumentsMessage();
    EXPECT_STREQ("定义的环境值：", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetEnvironmentNoFlags)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getEnvironmentNoFlags("MY_ENV_KEY");
    EXPECT_STREQ("环境值MY_ENV_KEY narg 必须> 0", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetRequiredEnvironmentArgMissing)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getRequiredEnvironmentArgMissing("MY_ENV_KEY");
    EXPECT_STREQ("必须定义环境值MY_ENV_KEY", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetJsonArgumentsMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getJsonArgumentsMessage();
    EXPECT_STREQ("可用的 JSON 参数值：", output.c_str());
}

TEST(ParserStringListInterfaceSimplifiedchinese, printgetXmlArgumentsMessage)
{
    ParserStringListInterfaceSimplifiedchinese testvar;
    parserstr output = testvar.getXmlArgumentsMessage();
    EXPECT_STREQ("可用的 XML 参数值：", output.c_str());
}

// Execute the tests
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

/**@} */
