/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateLangFilesV1.0.0.0 do not edit          
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <cstdio>
#include <cstring>
#include <sstream>
#include <gtest/gtest.h>
#include "ParserStringListInterface.h"
#include "ParserStringListInterfaceFrench.h"

/**
 * @file ParserStringListInterface_test.cpp
 * @defgroup LocalLanguageSelectionfrenchunittest Local language detection and selection utility french unit test
 * @ingroup LocalLanguageSelectionfrenchunittest
 * @{
 */

using namespace argparser;
using parser_str_stream = std::stringstream;

// NOLINTBEGIN
TEST(ParserStringListInterfaceFrench, fetchgetLangIsoCode)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getLangIsoCode();
    EXPECT_STREQ("fr", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetNotListTypeMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getNotListTypeMessage(3);
    EXPECT_STREQ("Seuls les arguments de type liste peuvent avoir un nombre d'arguments de 3", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetUnknownArgumentMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getUnknownArgumentMessage("--myKey");
    EXPECT_STREQ("Argument inconnu : --myKey", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetInvalidAssignmentMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getInvalidAssignmentMessage("--myKey");
    EXPECT_STREQ("Affectation non valide « --myKey »", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetAssignmentFailedMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getAssignmentFailedMessage("--myKey", "23");
    EXPECT_STREQ("Échec de l'affectation de « --myKey », « 23 »", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetMissingAssignmentMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getMissingAssignmentMessage("--myKey");
    EXPECT_STREQ("Valeur d'affectation manquante \"--myKey\"", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetMissingListAssignmentMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getMissingListAssignmentMessage("--myKey", 2, 1);
    EXPECT_STREQ("Valeur(s) d'affectation manquante(s) pour « --myKey ». Arguments attendus : 2. Arguments trouvés : 1.", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetTooManyAssignmentMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getTooManyAssignmentMessage("--myKey", 2, 1);
    EXPECT_STREQ("« --myKey » : trop de valeurs d'affectation. Arguments attendus : 2. Arguments trouvés : 1.", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetMissingArgumentMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getMissingArgumentMessage("--myKey");
    EXPECT_STREQ("L'argument requis « --myKey » est manquant", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetArgumentCreationError)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getArgumentCreationError("--myKey");
    EXPECT_STREQ("Échec de l'ajout d'argument : --myKey", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetUsageMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getUsageMessage();
    EXPECT_STREQ("Usage:", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetPositionalArgumentsMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getPositionalArgumentsMessage();
    EXPECT_STREQ("Arguments positionnels :", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetSwitchArgumentsMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getSwitchArgumentsMessage();
    EXPECT_STREQ("Arguments facultatifs :", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetHelpString)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getHelpString();
    EXPECT_STREQ("afficher ce message d'aide et quitter", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetEnvArgumentsMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getEnvArgumentsMessage();
    EXPECT_STREQ("Valeurs environnementales définies :", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetEnvironmentNoFlags)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getEnvironmentNoFlags("MY_ENV_KEY");
    EXPECT_STREQ("La valeur d'environnement MY_ENV_KEY narg doit être > 0", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetRequiredEnvironmentArgMissing)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getRequiredEnvironmentArgMissing("MY_ENV_KEY");
    EXPECT_STREQ("La valeur d'environnement MY_ENV_KEY doit être définie", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetJsonArgumentsMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getJsonArgumentsMessage();
    EXPECT_STREQ("Valeurs d'argument JSON disponibles :", output.c_str());
}

TEST(ParserStringListInterfaceFrench, printgetXmlArgumentsMessage)
{
    ParserStringListInterfaceFrench testvar;
    parserstr output = testvar.getXmlArgumentsMessage();
    EXPECT_STREQ("Valeurs d'argument XML disponibles :", output.c_str());
}

// NOLINTEND
// Execute the tests
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

/**@}*/
