/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike
* 
* MIT License
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in
* the Software without restriction, including without limitation the rights to
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:
* 
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
* 
* 
* This file was autogenerated by GenerateLangFilesV0.4.1.0 do not edit
* 
* ----------------------------------------------------------------------------*/

// Includes
#include <cstdio>
#include <cstring>
#include "ParserStringListInterface.h"

#pragma once
using namespace argparser;
/**
 * @brief Language specific parser error/help string generation interface
 */
class ParserStringListInterfaceEnglish final : public ParserStringListInterface
{
    public:
        ParserStringListInterfaceEnglish() = default;
        ParserStringListInterfaceEnglish(const ParserStringListInterfaceEnglish& other) = default;
        ParserStringListInterfaceEnglish(ParserStringListInterfaceEnglish&& other) = default;
        ParserStringListInterfaceEnglish& operator=(const ParserStringListInterfaceEnglish& other) = default;
        ParserStringListInterfaceEnglish& operator=(ParserStringListInterfaceEnglish&& other) = default;
        ~ParserStringListInterfaceEnglish() = default;

        parserstr getLangIsoCode() const final;

        parserstr getNotListTypeMessage(int nargs) final;
        parserstr getUnknownArgumentMessage(parserstr keyString) final;
        parserstr getInvalidAssignmentMessage(parserstr keyString) final;
        parserstr getAssignmentFailedMessage(parserstr keyString, parserstr valueString) final;
        parserstr getMissingAssignmentMessage(parserstr keyString) final;
        parserstr getMissingListAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound) final;
        parserstr getTooManyAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound) final;
        parserstr getMissingArgumentMessage(parserstr keyString) final;
        parserstr getArgumentCreationError(parserstr keyString) final;
        parserstr getUsageMessage() const final;
        parserstr getPositionalArgumentsMessage() const final;
        parserstr getSwitchArgumentsMessage() const final;
        parserstr getHelpString() const final;
        parserstr getEnvArgumentsMessage() const final;
        parserstr getEnvironmentNoFlags(parserstr envKeyString) final;
        parserstr getRequiredEnvironmentArgMissing(parserstr envKeyString) final;
        parserstr getJsonArgumentsMessage() const final;
        parserstr getXmlArgumentsMessage() const final;
}; // end of ParserStringListInterfaceEnglish class
