/*------------------------------------------------------------------------------
* Copyright (c) 2025 Randal Eike                                                
*                                                                               
* MIT License                                                                   
*                                                                               
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* self software and associated documentation files (the "Software"), to deal in 
* the Software without restriction, including without limitation the rights to  
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
* of the Software, and to permit persons to whom the Software is furnished to do
* so, subject to the following conditions:                                      
*                                                                               
* The above copyright notice and self permission notice shall be included in all
* copies or substantial portions of the Software.                               
*                                                                               
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.                                                                     
*                                                                               
*                                                                               
* This file was autogenerated by GenerateBaseLangFilesV1.0.0.0 do not edit      
*                                                                               
* ----------------------------------------------------------------------------*/

// Includes
#include <cstddef>
#include <cstdlib>
#include <memory>
#include <string>

/**
 * @file ParserStringListInterface.h
 * @defgroup LocalLanguageSelection Local language detection and selection utility
 * @ingroup LocalLanguageSelection
 * @{
 */
#pragma once

using parserstr = std::string;          ///< Standard parser string definition
using parserchar = char;                ///< Standard parser character definition

namespace argparser {

/**
 * @brief Parser error/help string generation interface
 */
class ParserStringListInterface
{
    public:
        /**
         * @brief Construct a new ParserStringListInterface object
         * 
         */
        ParserStringListInterface() = default;

        /**
         * @brief Copy constructor for a new ParserStringListInterface object
         * 
         * @param other Reference to object to copy
         * 
         */
        ParserStringListInterface(const ParserStringListInterface& other) = default;

        /**
         * @brief Move constructor for a new ParserStringListInterface object
         * 
         * @param other Reference to object to move
         * 
         */
        ParserStringListInterface(ParserStringListInterface&& other) = default;

        /**
         * @brief Equate constructor for a new ParserStringListInterface object
         * 
         * @param other Reference to object to copy
         * 
         * @return ParserStringListInterface& - *this
         */
        ParserStringListInterface& operator=(const ParserStringListInterface& other) = default;

        /**
         * @brief Equate move constructor for a new ParserStringListInterface object
         * 
         * @param other Reference to object to move
         * 
         * @return ParserStringListInterface& - *this
         */
        ParserStringListInterface& operator=(ParserStringListInterface&& other) = default;

        /**
         * @brief Destructor for ParserStringListInterface object
         * 
         */
        virtual ~ParserStringListInterface() = default;

        /**
         * @brief Get the ISO 639 set 1 language code for this object
         * 
         * @return parserstr - ISO 639 set 1 language code
         */
        [[nodiscard]] virtual parserstr getLangIsoCode() const = 0;

        /**
         * @brief Return non-list varg error message
         * 
         * @param nargs input nargs value
         * 
         * @return parserstr - Non-list varg error message
         */
        [[nodiscard]] virtual parserstr getNotListTypeMessage(int nargs) = 0;

        /**
         * @brief Return unknown parser key error message
         * 
         * @param keyString Unknown key
         * 
         * @return parserstr - Unknown parser key error message
         */
        [[nodiscard]] virtual parserstr getUnknownArgumentMessage(parserstr keyString) = 0;

        /**
         * @brief Return varg invalid assignment error message
         * 
         * @param keyString Error key
         * 
         * @return parserstr - Varg key invalid assignment error message
         */
        [[nodiscard]] virtual parserstr getInvalidAssignmentMessage(parserstr keyString) = 0;

        /**
         * @brief Return varg assignment failed error message
         * 
         * @param keyString Error key
         * @param valueString Assignment value
         * 
         * @return parserstr - Varg key assignment failed error message
         */
        [[nodiscard]] virtual parserstr getAssignmentFailedMessage(parserstr keyString, parserstr valueString) = 0;

        /**
         * @brief Return varg missing assignment error message
         * 
         * @param keyString Error key
         * 
         * @return parserstr - Varg key missing value assignment error message
         */
        [[nodiscard]] virtual parserstr getMissingAssignmentMessage(parserstr keyString) = 0;

        /**
         * @brief Return varg missing list value assignment error message
         * 
         * @param keyString Error key
         * @param nargsExpected Expected assignment list length
         * @param nargsFound Input assignment list length
         * 
         * @return parserstr - Varg key input value list too short error message
         */
        [[nodiscard]] virtual parserstr getMissingListAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound) = 0;

        /**
         * @brief Return varg missing list value assignment error message
         * 
         * @param keyString Error key
         * @param nargsExpected Expected assignment list length
         * @param nargsFound Input assignment list length
         * 
         * @return parserstr - Varg key input value list too long error message
         */
        [[nodiscard]] virtual parserstr getTooManyAssignmentMessage(parserstr keyString, size_t nargsExpected, size_t nargsFound) = 0;

        /**
         * @brief Return required varg missing error message
         * 
         * @param keyString Error key
         * 
         * @return parserstr - Required varg key missing error message
         */
        [[nodiscard]] virtual parserstr getMissingArgumentMessage(parserstr keyString) = 0;

        /**
         * @brief Return parser add varg failure error message
         * 
         * @param keyString Error key
         * 
         * @return parserstr - Parser varg add failure message
         */
        [[nodiscard]] virtual parserstr getArgumentCreationError(parserstr keyString) = 0;

        /**
         * @brief Return usage help message
         * 
         * @return parserstr - Usage help message
         */
        [[nodiscard]] virtual parserstr getUsageMessage() const = 0;

        /**
         * @brief Return positional argument help message
         * 
         * @return parserstr - Positional argument help message
         */
        [[nodiscard]] virtual parserstr getPositionalArgumentsMessage() const = 0;

        /**
         * @brief Return optional argument help message
         * 
         * @return parserstr - Optional argument help message
         */
        [[nodiscard]] virtual parserstr getSwitchArgumentsMessage() const = 0;

        /**
         * @brief Return default help switch help message
         * 
         * @return parserstr - Default help argument help message
         */
        [[nodiscard]] virtual parserstr getHelpString() const = 0;

        /**
         * @brief Return environment parser argument help header
         * 
         * @return parserstr - Environment parser argument help header message
         */
        [[nodiscard]] virtual parserstr getEnvArgumentsMessage() const = 0;

        /**
         * @brief Return environment parser add flag varg failure error message
         * 
         * @param envKeyString Flag key
         * 
         * @return parserstr - Environment parser add flag varg failure message
         */
        [[nodiscard]] virtual parserstr getEnvironmentNoFlags(parserstr envKeyString) = 0;

        /**
         * @brief Return environment parser required varg missing error message
         * 
         * @param envKeyString Flag key
         * 
         * @return parserstr - Environment parser required varg missing error message
         */
        [[nodiscard]] virtual parserstr getRequiredEnvironmentArgMissing(parserstr envKeyString) = 0;

        /**
         * @brief Return json parser argument help header
         * 
         * @return parserstr - JSON parser argument help header message
         */
        [[nodiscard]] virtual parserstr getJsonArgumentsMessage() const = 0;

        /**
         * @brief Return xml parser argument help header
         * 
         * @return parserstr - XML parser argument help header message
         */
        [[nodiscard]] virtual parserstr getXmlArgumentsMessage() const = 0;

        /**
         * @brief Determine the OS use OS specific functions to determine the correct local languagebased on the OS specific
         * local language setting and return the correct class object
         * 
         * @return std::shared_ptr<ParserStringListInterface> - Shared pointer to ParserStringListInterface<lang> based on OS
         *                                        local language
         */
        static std::shared_ptr<ParserStringListInterface> getLocalParserStringListInterface();
}; // end of ParserStringListInterface class

}; // end of namespace argparser
/**@}*/
