.TH "varg/inc/varg_clib_shared.h" 3 "Wed Feb 19 2025" "Version 0.9.2.0" "argparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
varg/inc/varg_clib_shared.h
.SH SYNOPSIS
.br
.PP
\fC#include 'varg_intf\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcvarptr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for argparse from the source code\&.
